name: Build and upload wrapper
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Building
    steps:

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Create work directory
        run: mkdir work

      - name: Create bin directory
        run: mkdir bin

      - name: Build
        run: |
          miner_name="tnn-miner"
          version="v0.4.0.b2.3.1"
          
          asset_name="${miner_name}-${version}"
          archive="bin/${asset_name}.tar.gz"
          cp -r ./wrapper ./work/${miner_name}
          sed "s/^MINER_NAME=minername/MINER_NAME=$miner_name/g" -i ./work/${miner_name}/h-manifest.conf
          sed 's/^ver="custom"/ver="${version}"/g' -i ./work/${miner_name}/h-stats.sh
          sed "s/^EXTERNAL_NAME=minername/EXTERNAL_NAME=$miner_name/g" -i ./work/${miner_name}/mmp-external.conf
          sed "s/^EXTERNAL_VERSION=custom/EXTERNAL_VERSION=$version/g" -i ./work/${miner_name}/mmp-external.conf
          chmod +x ./work/${miner_name}/h-run.sh
          chmod +x ./work/${miner_name}/h-stats.sh
          chmod +x ./work/${miner_name}/${miner_name}
          chmod +x ./work/${miner_name}/mmp-stats.sh
          tar -czvf "${archive}" -C ./work ${miner_name}
          

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        
        with:
          files: |
            bin/*.tar.gz
          tag_name: "tnn-miner-0.4.0"
          token: ${{ secrets.token }}
